### ISSUE TITLE
Disabled Plugin No Admin Access

### ISSUE THREAD

**Issue by uksitebuilder** [billythekid/recaptchaguest#3]
Hi, I recently disabled this plugin in admin and now cannot access admin.

I get an Internal Server Error when requesting the admin login page.

Please advise.

**Comment by billythekid** [comment]
Hi @uksitebuilder I'll check this out now.

Can you tell me how you disabled it please? just in the plugins section or via composer uninstall etc?

**Comment by uksitebuilder** [comment]
Hi, managed to sort it now

For reference this is what happened.

I disabled the plugin via the admin plugins section.

To fix, I dived in to the DB - plugins table and deleted the entry from the table and now  I can access the admin again.

**Comment by billythekid** [comment]
@uksitebuilder cheers for the info. I was able to disable the plugin and it was fine but I found if I disabled the recaptcha plugin I am getting an error so fixing this now.

Thanks for your report.

**Comment by uksitebuilder** [comment]
No problem - Thanks for the great plugin
